/**
 * Refresh src/data/htb.ts from the HackTheBox API.
 *
 * Run modes:
 *   node scripts/update-htb.mjs --inspect   print the raw API payloads
 *   node scripts/update-htb.mjs --dry-run   show what would change, write nothing
 *   node scripts/update-htb.mjs             rewrite the file
 *
 * The token comes from HTB_TOKEN in the environment and is never written to
 * disk or logged. v4 is not a documented public contract, so field names are
 * resolved from a list of candidates and any figure that cannot be found keeps
 * its committed value: a shifted API should leave the site stale, never blank.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const FILE = 'src/data/htb.ts';
const API = 'https://labs.hackthebox.com/api/v4';
// Either name works, so a local shell and the CI secret need not agree.
const token = process.env.HTB_TOKEN || process.env.HTB_API;
const argv = new Set(process.argv.slice(2));

if (!token) {
  console.error('No token. Set HTB_TOKEN or HTB_API in the environment.');
  process.exit(1);
}

const get = async (path) => {
  const res = await fetch(`${API}${path}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/json', 'User-Agent': 'certifa.net-stats' },
  });
  if (!res.ok) throw new Error(`${path} -> ${res.status} ${res.statusText}`);
  return res.json();
};

/** First candidate key that holds a usable value; undefined if none do. */
const pick = (obj, ...keys) => {
  for (const k of keys) {
    const v = k.split('.').reduce((o, part) => (o == null ? o : o[part]), obj);
    if (v !== undefined && v !== null && v !== '') return v;
  }
};

const current = readFileSync(FILE, 'utf8');
/** Committed value, used as the fallback whenever the API does not supply one. */
const committed = (key) => {
  const m = current.match(new RegExp(`${key}:\s*'?([^,'\n]+)'?`));
  return m ? (isNaN(+m[1]) ? m[1].trim() : +m[1]) : undefined;
};

const info = await get('/user/info');
const id = pick(info, 'info.id', 'id');
if (!id) throw new Error('could not resolve the user id from /user/info');

const profile = (await get(`/user/profile/basic/${id}`)).profile ?? {};

if (argv.has('--inspect')) {
  /* This output is read from a public Actions log, and /user/info carries
     contact details that have no business being there. Drop anything that
     looks personal or credential-shaped, and mask stray email addresses in
     values, before printing. */
  const SENSITIVE = /email|mail|token|secret|password|phone|address|ip$|ssn|dob|birth/i;
  const clean = (v) => {
    if (Array.isArray(v)) return v.map(clean);
    if (v && typeof v === 'object') {
      return Object.fromEntries(
        Object.entries(v)
          .filter(([k]) => !SENSITIVE.test(k))
          .map(([k, val]) => [k, clean(val)]),
      );
    }
    if (typeof v === 'string') return v.replace(/[^\s@]+@[^\s@]+\.[^\s@]+/g, '[redacted]');
    return v;
  };
  console.log(JSON.stringify({ info: clean(info), profile: clean(profile) }, null, 2));
  process.exit(0);
}

const next = {
  rank:        pick(profile, 'rank') ?? committed('rank'),
  level:       pick(profile, 'level', 'current_rank_progress') ?? committed('level'),
  points:      pick(profile, 'points') ?? committed('points'),
  machines:    pick(profile, 'user_owns', 'machine_owns', 'user_bloods') ?? committed('machines'),
  challenges:  pick(profile, 'challenge_owns.solved', 'challenge_owns') ?? committed('challenges'),
  globalRank:  pick(profile, 'ranking', 'rank_id', 'global_ranking') ?? committed('globalRank'),
  xpCurrent:   pick(profile, 'current_rank_progress', 'xp.current') ?? committed('current'),
  xpNext:      pick(profile, 'next_rank_points', 'xp.next') ?? committed('next'),
};

for (const [k, v] of Object.entries(next)) {
  if (v === undefined) throw new Error(`no value and no fallback for ${k}; refusing to write a blank stat`);
}

const out = `/**
 * HackTheBox profile figures.
 *
 * Generated by scripts/update-htb.mjs, which a scheduled workflow runs. Edit
 * that script rather than this file: a sync will overwrite anything by hand.
 * Every page reads from here, including the client-side module.
 *
 * Last synced: ${new Date().toISOString().slice(0, 10)}.
 */
export const htb = {
  rank: '${next.rank}',
  level: ${next.level},
  points: ${next.points},
  machines: ${next.machines},
  challenges: ${next.challenges},
  globalRank: ${next.globalRank},
  /** Progress through the current level, not a lifetime total. */
  xp: { current: ${next.xpCurrent}, next: ${next.xpNext} },
} as const;

/**
 * The XP bar's fill. Derived, so it cannot drift from the XP line beside it.
 */
export const xpFraction = htb.xp.current / htb.xp.next;

/** Long form, for the about vitals row. */
export const htbLine = \`\${htb.rank} · lvl \${htb.level} · global #\${htb.globalRank}\`;

/** Short form, for the footer and other tight spots. */
export const htbShort = \`\${htb.rank} · global #\${htb.globalRank}\`;
`;

if (argv.has('--dry-run')) {
  console.log(out);
  process.exit(0);
}

writeFileSync(FILE, out);
console.log(`updated ${FILE}: ${next.rank} lvl ${next.level}, ${next.machines} machines, global #${next.globalRank}`);
