/**
 * HackTheBox profile figures.
 *
 * Generated by scripts/update-htb.mjs, which a scheduled workflow runs. Edit
 * that script rather than this file: a sync will overwrite anything by hand.
 * Every page reads from here, including the client-side module.
 *
 * Last synced: 2026-08-23.
 */
export const htb = {
  rank: 'Pro Hacker',
  level: 58.52,
  points: 600,
  machines: 75,
  challenges: 34,
  globalRank: 468,
  /** Progress through the current level, not a lifetime total. */
  xp: { current: 58.52, next: 41.74100000000001 },
} as const;

/**
 * The XP bar's fill. Derived, so it cannot drift from the XP line beside it.
 */
export const xpFraction = htb.xp.current / htb.xp.next;

/** Long form, for the about vitals row. */
export const htbLine = `${htb.rank} · lvl ${htb.level} · global #${htb.globalRank}`;

/** Short form, for the footer and other tight spots. */
export const htbShort = `${htb.rank} · global #${htb.globalRank}`;
